package neu.edu.entity;
// Generated Dec 8, 2016 10:03:32 AM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MenuItems generated by hbm2java
 */
public class MenuItems implements java.io.Serializable {

	private Integer menuItemsId;
	private Restaurant restaurant;
	private String itemName;
	private String description;
	private String price;
	private String category;
	private Set restaurantOrdersForMenuItem2 = new HashSet(0);
	private Set restaurantOrdersForMenuItem3 = new HashSet(0);
	private Set restaurantOrdersForMenuItem1 = new HashSet(0);

	public MenuItems() {
	}

	public MenuItems(Restaurant restaurant, String itemName, String description, String price, String category,
			Set restaurantOrdersForMenuItem2, Set restaurantOrdersForMenuItem3, Set restaurantOrdersForMenuItem1) {
		this.restaurant = restaurant;
		this.itemName = itemName;
		this.description = description;
		this.price = price;
		this.category = category;
		this.restaurantOrdersForMenuItem2 = restaurantOrdersForMenuItem2;
		this.restaurantOrdersForMenuItem3 = restaurantOrdersForMenuItem3;
		this.restaurantOrdersForMenuItem1 = restaurantOrdersForMenuItem1;
	}

	public Integer getMenuItemsId() {
		return this.menuItemsId;
	}

	public void setMenuItemsId(Integer menuItemsId) {
		this.menuItemsId = menuItemsId;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public Set getRestaurantOrdersForMenuItem2() {
		return this.restaurantOrdersForMenuItem2;
	}

	public void setRestaurantOrdersForMenuItem2(Set restaurantOrdersForMenuItem2) {
		this.restaurantOrdersForMenuItem2 = restaurantOrdersForMenuItem2;
	}

	public Set getRestaurantOrdersForMenuItem3() {
		return this.restaurantOrdersForMenuItem3;
	}

	public void setRestaurantOrdersForMenuItem3(Set restaurantOrdersForMenuItem3) {
		this.restaurantOrdersForMenuItem3 = restaurantOrdersForMenuItem3;
	}

	public Set getRestaurantOrdersForMenuItem1() {
		return this.restaurantOrdersForMenuItem1;
	}

	public void setRestaurantOrdersForMenuItem1(Set restaurantOrdersForMenuItem1) {
		this.restaurantOrdersForMenuItem1 = restaurantOrdersForMenuItem1;
	}

}
