package neu.edu.entity;
// Generated Dec 8, 2016 10:03:32 AM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements java.io.Serializable {

	private Integer restaurantId;
	private User user;
	private String restaurantName;
	private String location;
	private String cuisuine;
	private String phoneNumber;
	private String price;
	private String status;
	private String isDisabled;
	private Set reviewReplies = new HashSet(0);
	private Set restaurantOrders = new HashSet(0);
	private Set menuItemses = new HashSet(0);
	public String getIsDisabled() {
		return isDisabled;
	}

	public void setIsDisabled(String isDisabled) {
		this.isDisabled = isDisabled;
	}

	private Set reviews = new HashSet(0);

	public Restaurant() {
	}

	public Restaurant(String restaurantName) {
		this.restaurantName = restaurantName;
	}

	public Restaurant(User user, String restaurantName, String location, String cuisuine, String phoneNumber,String isDisabled,
			String price, String status, Set reviewReplies, Set restaurantOrders, Set menuItemses, Set reviews) {
		this.user = user;
		this.restaurantName = restaurantName;
		this.location = location;
		this.cuisuine = cuisuine;
		this.phoneNumber = phoneNumber;
		this.price = price;
		this.status = status;
		this.reviewReplies = reviewReplies;
		this.restaurantOrders = restaurantOrders;
		this.menuItemses = menuItemses;
		this.reviews = reviews;
		this.isDisabled = isDisabled;
	}

	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(Integer restaurantId) {
		this.restaurantId = restaurantId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getRestaurantName() {
		return this.restaurantName;
	}

	public void setRestaurantName(String restaurantName) {
		this.restaurantName = restaurantName;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getCuisuine() {
		return this.cuisuine;
	}

	public void setCuisuine(String cuisuine) {
		this.cuisuine = cuisuine;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getReviewReplies() {
		return this.reviewReplies;
	}

	public void setReviewReplies(Set reviewReplies) {
		this.reviewReplies = reviewReplies;
	}

	public Set getRestaurantOrders() {
		return this.restaurantOrders;
	}

	public void setRestaurantOrders(Set restaurantOrders) {
		this.restaurantOrders = restaurantOrders;
	}

	public Set getMenuItemses() {
		return this.menuItemses;
	}

	public void setMenuItemses(Set menuItemses) {
		this.menuItemses = menuItemses;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

}
