package neu.edu.entity;
// Generated Dec 8, 2016 10:03:32 AM by Hibernate Tools 5.1.0.CR1

import java.util.Date;

/**
 * RestaurantOrder generated by hbm2java
 */
public class RestaurantOrder implements java.io.Serializable {

	private Integer orderId;
	private MenuItems menuItemsByMenuItem2;
	private MenuItems menuItemsByMenuItem3;
	private MenuItems menuItemsByMenuItem1;
	private Restaurant restaurant;
	private User user;
	private String amount;
	private Date orderDate;
	private String status;
	private String paymentType;

	public RestaurantOrder() {
	}

	public RestaurantOrder(MenuItems menuItemsByMenuItem2, MenuItems menuItemsByMenuItem3,
			MenuItems menuItemsByMenuItem1, Restaurant restaurant, User user, String amount, Date orderDate,
			String status, String paymentType) {
		this.menuItemsByMenuItem2 = menuItemsByMenuItem2;
		this.menuItemsByMenuItem3 = menuItemsByMenuItem3;
		this.menuItemsByMenuItem1 = menuItemsByMenuItem1;
		this.restaurant = restaurant;
		this.user = user;
		this.amount = amount;
		this.orderDate = orderDate;
		this.status = status;
		this.paymentType = paymentType;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public MenuItems getMenuItemsByMenuItem2() {
		return this.menuItemsByMenuItem2;
	}

	public void setMenuItemsByMenuItem2(MenuItems menuItemsByMenuItem2) {
		this.menuItemsByMenuItem2 = menuItemsByMenuItem2;
	}

	public MenuItems getMenuItemsByMenuItem3() {
		return this.menuItemsByMenuItem3;
	}

	public void setMenuItemsByMenuItem3(MenuItems menuItemsByMenuItem3) {
		this.menuItemsByMenuItem3 = menuItemsByMenuItem3;
	}

	public MenuItems getMenuItemsByMenuItem1() {
		return this.menuItemsByMenuItem1;
	}

	public void setMenuItemsByMenuItem1(MenuItems menuItemsByMenuItem1) {
		this.menuItemsByMenuItem1 = menuItemsByMenuItem1;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAmount() {
		return this.amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

}
