package neu.edu.entity;
// Generated Dec 8, 2016 10:03:32 AM by Hibernate Tools 5.1.0.CR1

import java.util.Date;

/**
 * ReviewReply generated by hbm2java
 */
public class ReviewReply implements java.io.Serializable {

	private Integer replyId;
	private Restaurant restaurant;
	private Review review;
	private User user;
	private String comments;
	private Date reviewDate;

	public ReviewReply() {
	}

	public ReviewReply(Restaurant restaurant, Review review, User user, String comments, Date reviewDate) {
		this.restaurant = restaurant;
		this.review = review;
		this.user = user;
		this.comments = comments;
		this.reviewDate = reviewDate;
	}

	public Integer getReplyId() {
		return this.replyId;
	}

	public void setReplyId(Integer replyId) {
		this.replyId = replyId;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public Review getReview() {
		return this.review;
	}

	public void setReview(Review review) {
		this.review = review;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getReviewDate() {
		return this.reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

}
