package neu.edu.entity;
// Generated Dec 8, 2016 10:03:32 AM by Hibernate Tools 5.1.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Review generated by hbm2java
 */
public class Review implements java.io.Serializable {

	private Integer reviewId;
	private Restaurant restaurant;
	private User user;
	private String comments;
	private Date reviewDate;
	private Set reviewReplies = new HashSet(0);

	public Review() {
	}

	public Review(Restaurant restaurant, User user, String comments, Date reviewDate, Set reviewReplies) {
		this.restaurant = restaurant;
		this.user = user;
		this.comments = comments;
		this.reviewDate = reviewDate;
		this.reviewReplies = reviewReplies;
	}

	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getReviewDate() {
		return this.reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	public Set getReviewReplies() {
		return this.reviewReplies;
	}

	public void setReviewReplies(Set reviewReplies) {
		this.reviewReplies = reviewReplies;
	}

}
