package neu.edu.entity;
// Generated Dec 8, 2016 10:03:32 AM by Hibernate Tools 5.1.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String password;
	private Date age;
	private String gender;
	private String fullName;
	private String phoneNumber;
	private String email;
	private String address;
	private String userType;
	/*private String isDisabled;
	public String getIsDisabled() {
		return isDisabled;
	}

	public void setIsDisabled(String isDisabled) {
		this.isDisabled = isDisabled;
	}*/

	private Set restaurantOrders = new HashSet(0);
	private Set reviews = new HashSet(0);
	private Set reviewReplies = new HashSet(0);
	private Set userPaymentDetailses = new HashSet(0);
	private Set restaurants = new HashSet(0);

	public User() {
	}

	public User(String userName, String fullName, String phoneNumber, String email, String address, String userType) {
		this.userName = userName;
		this.fullName = fullName;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.address = address;
		this.userType = userType;
		//this.isDisabled = isDisabled;
	}

	public User(String userName, String password, Date age, String gender, String fullName, String phoneNumber,
			String email, String address, String userType, Set restaurantOrders, Set reviews, Set reviewReplies,
			Set userPaymentDetailses, Set restaurants) {
		this.userName = userName;
		this.password = password;
		this.age = age;
		this.gender = gender;
		this.fullName = fullName;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.address = address;
		this.userType = userType;
		this.restaurantOrders = restaurantOrders;
		this.reviews = reviews;
		this.reviewReplies = reviewReplies;
		this.userPaymentDetailses = userPaymentDetailses;
		this.restaurants = restaurants;
		//this.isDisabled = isDisabled;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getAge() {
		return this.age;
	}

	public void setAge(Date age) {
		this.age = age;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public Set getRestaurantOrders() {
		return this.restaurantOrders;
	}

	public void setRestaurantOrders(Set restaurantOrders) {
		this.restaurantOrders = restaurantOrders;
	}

	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}

	public Set getReviewReplies() {
		return this.reviewReplies;
	}

	public void setReviewReplies(Set reviewReplies) {
		this.reviewReplies = reviewReplies;
	}

	public Set getUserPaymentDetailses() {
		return this.userPaymentDetailses;
	}

	public void setUserPaymentDetailses(Set userPaymentDetailses) {
		this.userPaymentDetailses = userPaymentDetailses;
	}

	public Set getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set restaurants) {
		this.restaurants = restaurants;
	}

}
